apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "employee-platform.fullname" .) }}
type: Opaque
stringData:
  DATABASE_USERNAME: {{ .Values.secret.databaseUser | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}