apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "employee-platform.fullname" .) }}
  labels:
    {{- include "employee-platform.labels" (dict "root" . "component" "api") | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USERNAME: {{ .Values.secret.databaseUser | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}