apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-platform.postgres.service.fullname" . }}
spec:
  selector:
    app: {{ include "employee-platform.postgres.fullname" . }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  type: ClusterIP