apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-platform.postgres.fullname" . }}
  labels:
    {{- include "employee-platform.labels" (dict "root" . "component" "database") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "employee-platform.selectorLabels" (dict "root" . "component" "database") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-platform.selectorLabels" (dict "root" . "component" "database") | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-config" (include "employee-platform.fullname" .) }}
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secret" (include "employee-platform.fullname" .) }}
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secret" (include "employee-platform.fullname" .) }}
                  key: DATABASE_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistence.existingClaim }}