apiVersion: v1
data:
  DATABASE_PASSWORD: U3VwZXJTZWNyZXQxMjM=
  DATABASE_USERNAME: cG9zdGdyZXM=
  JWT_SECRET: ZW1wbG95ZWUtYXBpLXNlY3JldC1rZXk=
kind: Secret
metadata:
  name: employee-api-secret
  namespace: employee
type: Opaque
