name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (MAJOR.MINOR.PATCH)"
        required: true
        type: string

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4